# General site information
title = "Eclipse Layout Kernel"
baseurl = "https://www.eclipse.org/elk/"
languageCode = "en-us"

# These settings magically make it so that the site is browsable both
# online and offline. We especially like the latter part, because it
# allows us to ship our documentation with each release.
canonifyURLs = true
uglyURLs = true
relativeURLs = true

# Fixes issue 718 by keeping Hugo from lower-casing all file names,
# which invalidates our URLs
disablePathToLower = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
